### ISSUE TITLE
1.3.13.tar.gz has inconsistent version: filename has '1.3.13', but metadata has '0.0.0'.

### ISSUE THREAD

**Issue by markp2** [xmlsec/python-xmlsec#232]
I am getting pip install failures - apparently because the 1.3.13.tar.gz has inconsistent version: filename has '1.3.13', but metadata has '0.0.0'. This has the effect of continuing 1.3.13. -> 1.3.12 -> 1.3.11 etc. until it ultimately fails. See below.

A workaround is to use Pips legacy resolver```sudo -H pip3 install --use-deprecated=legacy-resolver -U xmlsec ```

mark@MarksMacBookM1 source %  sudo -H pip3 install -U  --no-cache-dir xmlsec
Requirement already satisfied: xmlsec in /opt/homebrew/lib/python3.10/site-packages (0.0.0)
Collecting xmlsec
  Downloading xmlsec-1.3.13.tar.gz (64 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.6/64.6 kB 7.3 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Discarding https://files.pythonhosted.org/packages/37/9f/342d4562eac99178d0d515c780285e107c6828cefad37d02f05b7b7d8751/xmlsec-1.3.13.tar.gz (from https://pypi.org/simple/xmlsec/) (requires-python:>=3.5): Requested xmlsec from https://files.pythonhosted.org/packages/37/9f/342d4562eac99178d0d515c780285e107c6828cefad37d02f05b7b7d8751/xmlsec-1.3.13.tar.gz has inconsistent version: filename has '1.3.13', but metadata has '0.0.0'
  Downloading xmlsec-1.3.12.tar.gz (64 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.2/64.2 kB 344.0 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Discarding https://files.pythonhosted.org/packages/70/d7/83ac0d43bb92333c8ba3d9be97b85d1b2856ff9f32cebfc87b0e733339cc/xmlsec-1.3.12.tar.gz (from https://pypi.org/simple/xmlsec/) (requires-python:>=3.5): Requested xmlsec from https://files.pythonhosted.org/packages/70/d7/83ac0d43bb92333c8ba3d9be97b85d1b2856ff9f32cebfc87b0e733339cc/xmlsec-1.3.12.tar.gz has inconsistent version: filename has '1.3.12', but metadata has '0.0.0'
  Downloading xmlsec-1.3.11.tar.gz (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.3/61.3 kB 97.6 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Discarding https://files.pythonhosted.org/packages/ff/dd/0893ae620bfe3537eaa91c3a24e70dceba616b0cc71ed8e9fe9d0289fe34/xmlsec-1.3.11.tar.gz (from https://pypi.org/simple/xmlsec/) (requires-python:>=3.5): Requested xmlsec from https://files.pythonhosted.org/packages/ff/dd/0893ae620bfe3537eaa91c3a24e70dceba616b0cc71ed8e9fe9d0289fe34/xmlsec-1.3.11.tar.gz has inconsistent version: filename has '1.3.11', but metadata has '0.0.0'
  Downloading xmlsec-1.3.10.tar.gz (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.3/62.3 kB 2.9 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Discarding https://files.pythonhosted.org/packages/ca/a0/0b6f01fa1f138276e776dc31f1627be795a93e2722066db037444d956ee0/xmlsec-1.3.10.tar.gz (from https://pypi.org/simple/xmlsec/) (requires-python:>=3.5): Requested xmlsec from https://files.pythonhosted.org/packages/ca/a0/0b6f01fa1f138276e776dc31f1627be795a93e2722066db037444d956ee0/xmlsec-1.3.10.tar.gz has inconsistent version: filename has '1.3.10', but metadata has '0.0.0'
  Downloading xmlsec-1.3.9.tar.gz (62 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.6/62.6 kB 8.1 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Discarding https://files.pythonhosted.org/packages/47/61/b466ff0c8aa87ff033de8349d5f56d44336b67a77c092d3162a5f9e35ee8/xmlsec-1.3.9.tar.gz (from https://pypi.org/simple/xmlsec/) (requires-python:>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*): Requested xmlsec from https://files.pythonhosted.org/packages/47/61/b466ff0c8aa87ff033de8349d5f56d44336b67a77c092d3162a5f9e35ee8/xmlsec-1.3.9.tar.gz has inconsistent version: filename has '1.3.9', but metadata has '0.0.0'
  Downloading xmlsec-1.3.8.tar.gz (59 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.4/59.4 kB 14.7 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Discarding https://files.pythonhosted.org/packages/c3/e5/3e3183715fb3f98bd1ad44a7cc4a278bfeb800b9e9c2d50fe15f8522e548/xmlsec-1.3.8.tar.gz (from https://pypi.org/simple/xmlsec/) (requires-python:>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*): Requested xmlsec from https://files.pythonhosted.org/packages/c3/e5/3e3183715fb3f98bd1ad44a7cc4a278bfeb800b9e9c2d50fe15f8522e548/xmlsec-1.3.8.tar.gz has inconsistent version: filename has '1.3.8', but metadata has '0.0.0'
  Downloading xmlsec-1.3.3.tar.gz (29 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: pkgconfig in /opt/homebrew/lib/python3.10/site-packages (from xmlsec) (1.5.5)
Requirement already satisfied: lxml>=3.0 in /opt/homebrew/lib/python3.10/site-packages (from xmlsec) (4.9.1)
Building wheels for collected packages: xmlsec
  Building wheel for xmlsec (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [38 lines of output]
      /opt/homebrew/lib/python3.10/site-packages/setuptools/dist.py:771: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
        warnings.warn(
      /opt/homebrew/lib/python3.10/site-packages/setuptools/dist.py:771: UserWarning: Usage of dash-separated 'build-requires' will not be supported in future versions. Please use the underscore name 'build_requires' instead
        warnings.warn(
      /opt/homebrew/lib/python3.10/site-packages/setuptools/dist.py:771: UserWarning: Usage of dash-separated 'upload-dir' will not be supported in future versions. Please use the underscore name 'upload_dir' instead
        warnings.warn(
      running bdist_wheel
      running build
      running build_ext
      building 'xmlsec' extension
      creating build
      creating build/temp.macosx-12-arm64-cpython-310
      creating build/temp.macosx-12-arm64-cpython-310/private
      creating build/temp.macosx-12-arm64-cpython-310/private/tmp
      creating build/temp.macosx-12-arm64-cpython-310/private/tmp/pip-install-nc4uyq5v
      creating build/temp.macosx-12-arm64-cpython-310/private/tmp/pip-install-nc4uyq5v/xmlsec_48cb4d05ce334f9090a534f5a83c437b
      creating build/temp.macosx-12-arm64-cpython-310/private/tmp/pip-install-nc4uyq5v/xmlsec_48cb4d05ce334f9090a534f5a83c437b/src
      clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk -DMODULE_NAME=xmlsec -DMODULE_VERSION=1.3.3 -D__XMLSEC_FUNCTION__=__func__ -DXMLSEC_NO_SIZE_T -DXMLSEC_NO_GOST=1 -DXMLSEC_NO_GOST2012=1 -DXMLSEC_NO_CRYPTO_DYNAMIC_LOADING=1 -DXMLSEC_CRYPTO_OPENSSL=1 -I/opt/homebrew/Cellar/libxmlsec1/1.2.34_1/include/xmlsec1 -I/opt/homebrew/opt/openssl@1.1/include -I/opt/homebrew/opt/openssl@1.1/include/openssl -I/opt/homebrew/lib/python3.10/site-packages/lxml/includes -I/opt/homebrew/lib/python3.10/site-packages/lxml -I/opt/homebrew/lib/python3.10/site-packages/lxml/includes/__pycache__ -I/opt/homebrew/opt/python@3.10/Frameworks/Python.framework/Versions/3.10/include/python3.10 -c /private/tmp/pip-install-nc4uyq5v/xmlsec_48cb4d05ce334f9090a534f5a83c437b/src/constants.c -o build/temp.macosx-12-arm64-cpython-310/private/tmp/pip-install-nc4uyq5v/xmlsec_48cb4d05ce334f9090a534f5a83c437b/src/constants.o -g -std=c99 -fno-strict-aliasing -Wno-error=declaration-after-statement -Werror=implicit-function-declaration -Os
      /private/tmp/pip-install-nc4uyq5v/xmlsec_48cb4d05ce334f9090a534f5a83c437b/src/constants.c:288:5: error: use of undeclared identifier 'xmlSecXkmsNs'
          PYXMLSEC_ADD_NS_CONSTANT(XkmsNs, "XKMS");
          ^
      /private/tmp/pip-install-nc4uyq5v/xmlsec_48cb4d05ce334f9090a534f5a83c437b/src/constants.c:278:45: note: expanded from macro 'PYXMLSEC_ADD_NS_CONSTANT'
          tmp = PyString_FromString((const char*)(JOIN(xmlSec, name))); \
                                                  ^
      /private/tmp/pip-install-nc4uyq5v/xmlsec_48cb4d05ce334f9090a534f5a83c437b/src/common.h:19:19: note: expanded from macro 'JOIN'
      #define JOIN(X,Y) DO_JOIN1(X,Y)
                        ^
      /private/tmp/pip-install-nc4uyq5v/xmlsec_48cb4d05ce334f9090a534f5a83c437b/src/common.h:20:23: note: expanded from macro 'DO_JOIN1'
      #define DO_JOIN1(X,Y) DO_JOIN2(X,Y)
                            ^
      /private/tmp/pip-install-nc4uyq5v/xmlsec_48cb4d05ce334f9090a534f5a83c437b/src/common.h:21:23: note: expanded from macro 'DO_JOIN2'
      #define DO_JOIN2(X,Y) X##Y
                            ^
      <scratch space>:122:1: note: expanded from here
      xmlSecXkmsNs
      ^
      1 error generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for xmlsec
  Running setup.py clean for xmlsec
Failed to build xmlsec
Installing collected packages: xmlsec
  Attempting uninstall: xmlsec
    Found existing installation: xmlsec 0.0.0
    Uninstalling xmlsec-0.0.0:
      Successfully uninstalled xmlsec-0.0.0
  Running setup.py install for xmlsec ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for xmlsec did not run successfully.
  │ exit code: 1
  ╰─> [40 lines of output]
      /opt/homebrew/lib/python3.10/site-packages/setuptools/dist.py:771: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
        warnings.warn(
      /opt/homebrew/lib/python3.10/site-packages/setuptools/dist.py:771: UserWarning: Usage of dash-separated 'build-requires' will not be supported in future versions. Please use the underscore name 'build_requires' instead
        warnings.warn(
      /opt/homebrew/lib/python3.10/site-packages/setuptools/dist.py:771: UserWarning: Usage of dash-separated 'upload-dir' will not be supported in future versions. Please use the underscore name 'upload_dir' instead
        warnings.warn(
      running install
      /opt/homebrew/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_ext
      building 'xmlsec' extension
      creating build
      creating build/temp.macosx-12-arm64-cpython-310
      creating build/temp.macosx-12-arm64-cpython-310/private
      creating build/temp.macosx-12-arm64-cpython-310/private/tmp
      creating build/temp.macosx-12-arm64-cpython-310/private/tmp/pip-install-nc4uyq5v
      creating build/temp.macosx-12-arm64-cpython-310/private/tmp/pip-install-nc4uyq5v/xmlsec_48cb4d05ce334f9090a534f5a83c437b
      creating build/temp.macosx-12-arm64-cpython-310/private/tmp/pip-install-nc4uyq5v/xmlsec_48cb4d05ce334f9090a534f5a83c437b/src
      clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk -DMODULE_NAME=xmlsec -DMODULE_VERSION=1.3.3 -D__XMLSEC_FUNCTION__=__func__ -DXMLSEC_NO_SIZE_T -DXMLSEC_NO_GOST=1 -DXMLSEC_NO_GOST2012=1 -DXMLSEC_NO_CRYPTO_DYNAMIC_LOADING=1 -DXMLSEC_CRYPTO_OPENSSL=1 -I/opt/homebrew/Cellar/libxmlsec1/1.2.34_1/include/xmlsec1 -I/opt/homebrew/opt/openssl@1.1/include -I/opt/homebrew/opt/openssl@1.1/include/openssl -I/opt/homebrew/lib/python3.10/site-packages/lxml/includes -I/opt/homebrew/lib/python3.10/site-packages/lxml -I/opt/homebrew/lib/python3.10/site-packages/lxml/includes/__pycache__ -I/opt/homebrew/opt/python@3.10/Frameworks/Python.framework/Versions/3.10/include/python3.10 -c /private/tmp/pip-install-nc4uyq5v/xmlsec_48cb4d05ce334f9090a534f5a83c437b/src/constants.c -o build/temp.macosx-12-arm64-cpython-310/private/tmp/pip-install-nc4uyq5v/xmlsec_48cb4d05ce334f9090a534f5a83c437b/src/constants.o -g -std=c99 -fno-strict-aliasing -Wno-error=declaration-after-statement -Werror=implicit-function-declaration -Os
      /private/tmp/pip-install-nc4uyq5v/xmlsec_48cb4d05ce334f9090a534f5a83c437b/src/constants.c:288:5: error: use of undeclared identifier 'xmlSecXkmsNs'
          PYXMLSEC_ADD_NS_CONSTANT(XkmsNs, "XKMS");
          ^
      /private/tmp/pip-install-nc4uyq5v/xmlsec_48cb4d05ce334f9090a534f5a83c437b/src/constants.c:278:45: note: expanded from macro 'PYXMLSEC_ADD_NS_CONSTANT'
          tmp = PyString_FromString((const char*)(JOIN(xmlSec, name))); \
                                                  ^
      /private/tmp/pip-install-nc4uyq5v/xmlsec_48cb4d05ce334f9090a534f5a83c437b/src/common.h:19:19: note: expanded from macro 'JOIN'
      #define JOIN(X,Y) DO_JOIN1(X,Y)
                        ^
      /private/tmp/pip-install-nc4uyq5v/xmlsec_48cb4d05ce334f9090a534f5a83c437b/src/common.h:20:23: note: expanded from macro 'DO_JOIN1'
      #define DO_JOIN1(X,Y) DO_JOIN2(X,Y)
                            ^
      /private/tmp/pip-install-nc4uyq5v/xmlsec_48cb4d05ce334f9090a534f5a83c437b/src/common.h:21:23: note: expanded from macro 'DO_JOIN2'
      #define DO_JOIN2(X,Y) X##Y
                            ^
      <scratch space>:122:1: note: expanded from here
      xmlSecXkmsNs
      ^
      1 error generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Rolling back uninstall of xmlsec
  Moving to /opt/homebrew/lib/python3.10/site-packages/xmlsec-0.0.0.dist-info/
   from /opt/homebrew/lib/python3.10/site-packages/~mlsec-0.0.0.dist-info
  Moving to /opt/homebrew/lib/python3.10/site-packages/xmlsec.cpython-310-darwin.so
   from /private/tmp/pip-uninstall-b9aut885/xmlsec.cpython-310-darwin.so
  Moving to /opt/homebrew/lib/python3.10/site-packages/xmlsec/
   from /opt/homebrew/lib/python3.10/site-packages/~mlsec
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> xmlsec

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
mark@MarksMacBookM1 source %

**Comment by hoefling** [comment]
Can't reproduce that:
```sh
$ pip download --no-cache-dir xmlsec
$ tar xfO xmlsec-1.3.13.tar.gz xmlsec-1.3.13/PKG-INFO | grep -i 'version:'
Metadata-Version: 2.1
Version: 1.3.13
$ tar xfO xmlsec-1.3.13.tar.gz xmlsec-1.3.13/src/xmlsec.egg-info/PKG-INFO | grep -i 'version:'
Metadata-Version: 2.1
Version: 1.3.13
```
What version of `pip` are you using? Try upgrading `pip` (and by chance `setuptools` as well) first:
```sh
$ python3 -m venv tst
$ source tst/bin/activate
(tst) $ pip install --upgrade pip setuptools
...
Successfully installed pip-22.2.2 setuptools-65.3.0
(tst) $ pip install xmlsec
```
Does the error still persist?

**Comment by markp2** [comment]
Thanks. I only have pip3 and it is 22.2.2

```
mark@MarksMacBookM1 source % pip3 --version
pip 22.2.2 from /opt/homebrew/lib/python3.10/site-packages/pip (python 3.10)
mark@MarksMacBookM1 source % setuptools --version
zsh: command not found: setuptools
```

**Comment by hoefling** [comment]
Again - does it fail in a fresh venv? Use the commands given at the bottom of my previous comment to reproduce.

**Comment by markp2** [comment]
That does work:

```
mark@MarksMacBookM1 source % python3 -m venv tst
mark@MarksMacBookM1 source % source tst/bin/activate
(tst) mark@MarksMacBookM1 source % pip install --upgrade pip setuptools
Requirement already satisfied: pip in ./tst/lib/python3.10/site-packages (22.2.2)
Requirement already satisfied: setuptools in ./tst/lib/python3.10/site-packages (63.4.3)
Collecting setuptools
  Using cached setuptools-65.3.0-py3-none-any.whl (1.2 MB)
Installing collected packages: setuptools
  Attempting uninstall: setuptools
    Found existing installation: setuptools 63.4.3
    Uninstalling setuptools-63.4.3:
      Successfully uninstalled setuptools-63.4.3
Successfully installed setuptools-65.3.0
(tst) mark@MarksMacBookM1 source % pip install xmlsec
Collecting xmlsec
  Downloading xmlsec-1.3.13.tar.gz (64 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.6/64.6 kB 1.9 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting lxml>=3.8
  Using cached lxml-4.9.1-cp310-cp310-macosx_12_0_arm64.whl
Building wheels for collected packages: xmlsec
  Building wheel for xmlsec (pyproject.toml) ... done
  Created wheel for xmlsec: filename=xmlsec-1.3.13-cp310-cp310-macosx_12_0_arm64.whl size=44989 sha256=edab7c228248f9f5aab14ac81f4684670f9295979ff7cb46b7604288d944526b
  Stored in directory: /Users/mark/Library/Caches/pip/wheels/4e/10/4f/db7ab2326b7ed5575ca8d5896571220217048e11c899e8f35f
Successfully built xmlsec
Installing collected packages: lxml, xmlsec
Successfully installed lxml-4.9.1 xmlsec-1.3.13
(tst) mark@MarksMacBookM1 source %   
```

**Comment by hoefling** [comment]
This isn't an issue with the package itself then, rather with the brewed environment - update `pip`/`setuptools` for the brewed python and you should be good.

**Comment by markp2** [comment]
Unfortunately I still have the issue after upgrading pip and setup tools in my non venv environment (brew). Using the -v flag I can see there is an Error in sitecustomize;   If I set PYTHONVERBOSE for traceback I see the 2 python Tracebacks in addition to the ERROR: No matching distribution found for xmlsec==1.3.12

```
  Traceback (most recent call last):
    File "/usr/local/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site.py", line 549, in execsitecustomize
      import sitecustomize
    File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
    File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
    File "<frozen importlib._bootstrap_external>", line 883, in exec_module
    File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
    File "/private/var/folders/3d/5td6p6fj7p3gk7nvkgltv29c0000gp/T/pip-build-env-5d5gilh6/site/sitecustomize.py", line 22, in <module>
      assert not path in sys.path
  AssertionError

  Traceback (most recent call last):
    File "/usr/local/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site.py", line 549, in execsitecustomize
      import sitecustomize
    File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
    File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
    File "<frozen importlib._bootstrap_external>", line 883, in exec_module
    File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
    File "/private/var/folders/3d/5td6p6fj7p3gk7nvkgltv29c0000gp/T/pip-build-env-5d5gilh6/site/sitecustomize.py", line 22, in <module>
      assert not path in sys.path
  AssertionError
```



```
Markss-MBP-9:source mark$ pip install --upgrade pip setuptools
Requirement already satisfied: pip in /usr/local/lib/python3.10/site-packages (22.2.2)
Requirement already satisfied: setuptools in /usr/local/lib/python3.10/site-packages (65.4.0)
Markss-MBP-9:source mark$ 
Markss-MBP-9:source mark$ pip -V
pip 22.2.2 from /usr/local/lib/python3.10/site-packages/pip (python 3.10)
Markss-MBP-9:source mark$ pip3 -V
pip 22.2.2 from /usr/local/lib/python3.10/site-packages/pip (python 3.10)

Markss-MBP-9:source mark$ pip3 install --no-cache-dir --force-reinstall -v  xmlsec==1.3.12
Using pip 22.2.2 from /usr/local/lib/python3.10/site-packages/pip (python 3.10)
Collecting xmlsec==1.3.12
  Downloading xmlsec-1.3.12.tar.gz (64 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.2/64.2 kB 81.4 MB/s eta 0:00:00
  Running command pip subprocess to install build dependencies
  Collecting setuptools>=42
    Using cached setuptools-65.4.0-py3-none-any.whl (1.2 MB)
  Collecting wheel
    Using cached wheel-0.37.1-py2.py3-none-any.whl (35 kB)
  Collecting setuptools_scm[toml]>=3.4
    Using cached setuptools_scm-7.0.5-py3-none-any.whl (42 kB)
  Collecting tomli>=1.0.0
    Using cached tomli-2.0.1-py3-none-any.whl (12 kB)
  Collecting typing-extensions
    Using cached typing_extensions-4.3.0-py3-none-any.whl (25 kB)
  Collecting packaging>=20.0
    Using cached packaging-21.3-py3-none-any.whl (40 kB)
  Collecting pyparsing!=3.0.5,>=2.0.2
    Using cached pyparsing-3.0.9-py3-none-any.whl (98 kB)
  Installing collected packages: wheel, typing-extensions, tomli, setuptools, pyparsing, packaging, setuptools_scm
  Successfully installed packaging-21.3 pyparsing-3.0.9 setuptools-65.4.0 setuptools_scm-7.0.5 tomli-2.0.1 typing-extensions-4.3.0 wheel-0.37.1
  Installing build dependencies ... done
  Running command Getting requirements to build wheel
  Error in sitecustomize; set PYTHONVERBOSE for traceback:
  AssertionError:
  Getting requirements to build wheel ... done
  Running command pip subprocess to install backend dependencies
  Collecting setuptools_scm[toml]>=3.4
    Using cached setuptools_scm-7.0.5-py3-none-any.whl (42 kB)
  Collecting setuptools
    Using cached setuptools-65.4.0-py3-none-any.whl (1.2 MB)
  Collecting tomli>=1.0.0
    Using cached tomli-2.0.1-py3-none-any.whl (12 kB)
  Collecting packaging>=20.0
    Using cached packaging-21.3-py3-none-any.whl (40 kB)
  Collecting typing-extensions
    Using cached typing_extensions-4.3.0-py3-none-any.whl (25 kB)
  Collecting pyparsing!=3.0.5,>=2.0.2
    Using cached pyparsing-3.0.9-py3-none-any.whl (98 kB)
  Installing collected packages: typing-extensions, tomli, setuptools, pyparsing, packaging, setuptools_scm
  Successfully installed packaging-21.3 pyparsing-3.0.9 setuptools-65.4.0 setuptools_scm-7.0.5 tomli-2.0.1 typing-extensions-4.3.0
  Installing backend dependencies ... done
  Running command Preparing metadata (pyproject.toml)
  Error in sitecustomize; set PYTHONVERBOSE for traceback:
  AssertionError:
  /usr/local/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/setuptools/_distutils/dist.py:264: UserWarning: Unknown distribution option: 'use_scm_version'
    warnings.warn(msg)
  running dist_info
  creating /private/var/folders/3d/5td6p6fj7p3gk7nvkgltv29c0000gp/T/pip-modern-metadata-s4eclfej/xmlsec.egg-info
  writing /private/var/folders/3d/5td6p6fj7p3gk7nvkgltv29c0000gp/T/pip-modern-metadata-s4eclfej/xmlsec.egg-info/PKG-INFO
  writing dependency_links to /private/var/folders/3d/5td6p6fj7p3gk7nvkgltv29c0000gp/T/pip-modern-metadata-s4eclfej/xmlsec.egg-info/dependency_links.txt
  writing requirements to /private/var/folders/3d/5td6p6fj7p3gk7nvkgltv29c0000gp/T/pip-modern-metadata-s4eclfej/xmlsec.egg-info/requires.txt
  writing top-level names to /private/var/folders/3d/5td6p6fj7p3gk7nvkgltv29c0000gp/T/pip-modern-metadata-s4eclfej/xmlsec.egg-info/top_level.txt
  writing manifest file '/private/var/folders/3d/5td6p6fj7p3gk7nvkgltv29c0000gp/T/pip-modern-metadata-s4eclfej/xmlsec.egg-info/SOURCES.txt'
  reading manifest file '/private/var/folders/3d/5td6p6fj7p3gk7nvkgltv29c0000gp/T/pip-modern-metadata-s4eclfej/xmlsec.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  no previously-included directories found matching '*/__pycache__'
  no previously-included directories found matching '.github'
  no previously-included directories found matching 'doc'
  warning: no previously-included files found matching '.appveyor.yml'
  warning: no previously-included files found matching '.editorconfig'
  warning: no previously-included files found matching '.travis.yml'
  warning: no previously-included files found matching '.gitattributes'
  warning: no previously-included files found matching '.gitignore'
  warning: no previously-included files found matching 'requirements-test.txt'
  warning: no previously-included files found matching 'requirements.txt'
  warning: no previously-included files found matching 'xmlsec_extra.py'
  warning: no previously-included files found matching 'xmlsec_setupinfo.py'
  adding license file 'LICENSE'
  writing manifest file '/private/var/folders/3d/5td6p6fj7p3gk7nvkgltv29c0000gp/T/pip-modern-metadata-s4eclfej/xmlsec.egg-info/SOURCES.txt'
  creating '/private/var/folders/3d/5td6p6fj7p3gk7nvkgltv29c0000gp/T/pip-modern-metadata-s4eclfej/xmlsec-0.0.0.dist-info'
  adding license file "LICENSE" (matched pattern "LICEN[CS]E*")
  Preparing metadata (pyproject.toml) ... done
  WARNING: Requested xmlsec==1.3.12 from https://files.pythonhosted.org/packages/70/d7/83ac0d43bb92333c8ba3d9be97b85d1b2856ff9f32cebfc87b0e733339cc/xmlsec-1.3.12.tar.gz, but installing version 0.0.0
Discarding https://files.pythonhosted.org/packages/70/d7/83ac0d43bb92333c8ba3d9be97b85d1b2856ff9f32cebfc87b0e733339cc/xmlsec-1.3.12.tar.gz (from https://pypi.org/simple/xmlsec/) (requires-python:>=3.5): Requested xmlsec==1.3.12 from https://files.pythonhosted.org/packages/70/d7/83ac0d43bb92333c8ba3d9be97b85d1b2856ff9f32cebfc87b0e733339cc/xmlsec-1.3.12.tar.gz has inconsistent version: filename has '1.3.12', but metadata has '0.0.0'
ERROR: Could not find a version that satisfies the requirement xmlsec==1.3.12 (from versions: 0.1.0, 0.1.1, 0.1.2, 0.2.0, 0.3.0, 0.3.1, 0.3.3, 0.4.0, 0.5.0, 0.6.0, 0.6.1, 1.0.1, 1.0.2.dev0, 1.0.3.dev0, 1.0.3, 1.0.4, 1.0.5, 1.0.6, 1.0.7, 1.0.8, 1.0.9, 1.1.0, 1.2.0, 1.3.1, 1.3.2, 1.3.3, 1.3.7, 1.3.8, 1.3.9, 1.3.10, 1.3.11, 1.3.12, 1.3.13)
ERROR: No matching distribution found for xmlsec==1.3.12
Markss-MBP-9:source mark$ 

```

**Comment by markp2** [comment]
Is there a way for me [or you] to modify the assert line to:

```assert not path in sys.path, (path, sys.path)```
