### ISSUE TITLE
Create a xmlsec-binary package

### ISSUE THREAD

**Issue by visuman** [xmlsec/python-xmlsec#243]
I have been using python-xmlsec for a while now, and I always create a .whl with xmlsec present in it as it's much easier to use.
And over the last 1 year, I've had multiple issues with building this .whl file because of some system dependencies and version conflicts.

It would be great if we can have xmlsec-binary.

Somewhat like how the pysqlite3 project does it:
https://pypi.org/project/pysqlite3-binary/
https://pypi.org/project/pysqlite3/

Or
https://pypi.org/project/psycopg2/
https://pypi.org/project/psycopg2-binary/

I believe this would be really helpful for a lot of folks .

**Comment by mxamin** [comment]
Duplicate https://github.com/xmlsec/python-xmlsec/issues/245.
We're gonna continue in https://github.com/xmlsec/python-xmlsec/issues/316.
