### ISSUE TITLE
Find and include new maintainers

### ISSUE THREAD

**Issue by mdgreenwald** [xmlsec/python-xmlsec#272]
Hi @hoefling, if you can find the time perhaps you could submit your project to: [https://adoptoposs.org](https://adoptoposs.org). They may be able to find additional maintainers to help contribute to this project so that it can continue to serve the python community.

>If you don't have co-maintainers for your open source project in mind yet, consider submitting your project to [Adoptoposs.org](https://adoptoposs.org/). Adoptoposs will list your project and also notify developers interested in the programming languages you use.
> Keep in mind to [document important details](https://opensource.com/business/15/5/write-better-docs) about your project to make it easier for people to help you. Start seeking out help early on and build a team of co-maintainers to keep your open source projects and yourself healthy.

Thank you,
Matthew

**Comment by eljeffeg** [comment]
It's not even like @hoefling is gone from GitHub.  He's on here regularly and while I appreciate the aspect of open source and the contribution, it's frustrating that he won't take 5 seconds to respond in one way or another.  A middle finger would be better than the silence.. at least then we'd know to fork and move on.

**Comment by mdgreenwald** [comment]
@jimjag Are you a contributor now?
