### ISSUE TITLE
Time to fork python-xmlsec?

### ISSUE THREAD

**Issue by jimjag** [xmlsec/python-xmlsec#275]
Considering that the current version of python-xmlsec is not compatible with the current version of libxmlsec1, and there appears to be no official progress or response regarding the future of this project, is it time to consider a fork?

**Comment by ayakael** [comment]
Perhaps, especially since a new round of changes in libxml 1.3.3 breaks python-xmlsec even after applying  https://github.com/xmlsec/python-xmlsec/pull/264.

Ref: https://github.com/xmlsec/python-xmlsec/issues/279

**Comment by nkukard** [comment]
> Considering that the current version of python-xmlsec is not compatible with the current version of libxmlsec1, and there appears to be no official progress or response regarding the future of this project, is it time to consider a fork?

Definitely sounds like an idea ... who is going to press the button though and do it?

**Comment by bgaifullin** [comment]
I this it would be better to add new maintainers for this project.
If someone wants, please write to me.

**Comment by jimjag** [comment]
I volunteer

**Comment by mxamin** [comment]
I also volunteer

**Comment by ryanhiebert** [comment]
I'm willing to help.

**Comment by bgaifullin** [comment]
@mxamin and @jimjag congratulations.
