### ISSUE TITLE
lxml 5.0.0 incompatibility - Arithmetic exception

### ISSUE THREAD

**Issue by eljeffeg** [xmlsec/python-xmlsec#277]
[lxml](https://lxml.de/5.0/changes-5.0.0.html) 5.0.0 was released on Dec 29th 2023.  This update causes an `Arithmetic exception (core dumped)` when using python-xmlsec.

Example code that would fail..
```py
import xmlsec
from lxml import etree
root = None
with open("sign4-in.xml") as f:
    root = etree.parse(f).getroot()
xmlsec.tree.add_ids(root, ["ID"])
```

**Comment by brianray** [comment]
also experiencing segfault with lxml-5

**Comment by nosnilmot** [comment]
Use `pip install --no-binary lxml lxml` to install lxml from source and link to system `libxml2`, same as `xmlsec`, to avoid conflicting `libxml2` libraries.
See also https://bugs.launchpad.net/lxml/+bug/1960668#yui_3_10_3_1_1705879387759_1639

**Comment by bgaifullin** [comment]
I am not sure, that need to build lxml from source every-time.

**Comment by nosnilmot** [comment]
> I am not sure, that need to build lxml from source every-time.

what are you not sure about?

`lxml` bundles it's own copy of `libxml2` which may be a different version from the library that `xmlsec` is linked against, the only way to ensure they are both using the same version is to rebuild `lxml`.

This is documented here: https://lxml.de/FAQ.html#my-application-crashes

**Comment by deronnax** [comment]
@eljeffeg you are on macOS, aren't you?

**Comment by eljeffeg** [comment]
Yes, I'll try and test it tonight or tomorrow.

**Comment by eljeffeg** [comment]
@deronnax I can confirm I was able to build the latest xmlsec on MacOS and it passed the example code posted in the issue description.
