### ISSUE TITLE
Release the new version

### ISSUE THREAD

**Issue by mxamin** [xmlsec/python-xmlsec#284]
Now that we have the fix for compliance with XMLsec v1.3.3, I guess we need to release a new version so we can close the related issue, trying to install with pip. 
@jimjag @bgaifullin What do you think? Do you think of any preparation/changes before the release.
I can create the tag and the release note but since I don't have access to pypi, I need your help with that.

**Comment by ayakael** [comment]
https://github.com/xmlsec/python-xmlsec/pull/253 will also be necessary for python 3.11 support, I believe. The code won't work as-is as it still references `xmlSecCryptoAppKeyLoad` rather than `xmlSecCryptoAppKeyLoadEx`. It can be merged, and adjusted after by replacing line 209 with `key->handle = xmlSecCryptoAppKeyLoad(engine_and_key_id, xmlSecKeyDataTypePrivate, xmlSecKeyDataFormatEngine, NULL, xmlSecCryptoAppGetDefaultPwdCallback(),`

**Comment by jimjag** [comment]
Both have been merged into HEAD

**Comment by ayakael** [comment]
Awesome! I made a mistake in the above comment. This final PR will fix things https://github.com/xmlsec/python-xmlsec/pull/285

**Comment by mxamin** [comment]
@ayakael #285 merged.

**Comment by ayakael** [comment]
Wicked! Build works on Alpine Linux using py3-lxml 4.94, py3-xmlsec 1.3.3 and python 3.11.

**Comment by mxamin** [comment]
With the new changes, you can't install the library using the old version of xmlsec1. I made a few changes to make it backward compatible: https://github.com/xmlsec/python-xmlsec/pull/286

**Comment by mxamin** [comment]
I also noticed that building the library would fail with the latest version of xmlsec1 (1.3.3) because of a typo: https://github.com/lsh123/xmlsec/pull/755

**Comment by pitbulk** [comment]
Thanks to everyone involved in this hard work, keeping the project alive.

[python3-saml](https://github.com/SAML-Toolkits/python3-saml) depends on this great library and we are so happy that you are fixing the installation conflicts reported.

The release of a new version is so close, thanks again!

**Comment by nosnilmot** [comment]
I strongly suggest you merge #246 (at least until #283 is resolved)

**Comment by ryanhiebert** [comment]
@nosnilmot afaict, that PR doesn’t block binary lxml for library users, it’s just for the library tests or something. I don’t see that it is referenced from setup.py.

**Comment by nosnilmot** [comment]
> that PR doesn’t block binary lxml for library users, it’s just for the library tests or something. I don’t see that it is referenced from setup.py.

oh boo, and from what I can tell there is no trivial way to specify 'no-binary' for dependencies installed by setup.py 😞

**Comment by jdoklovic** [comment]
is this going to be merged?

**Comment by jimjag** [comment]
We are at the point where, we think, all required and available PRs have been merged.

**Comment by mxamin** [comment]
> We are at the point where, we think, all required and available PRs have been merged.

Perfect, @jimjag  I can prepare the release (tag, change log, etc) but I don't have access to update the PyPI.

**Comment by jonathangreen** [comment]
You might want to consider merging https://github.com/xmlsec/python-xmlsec/pull/299 before the new release goes out, since it makes it much clearer when the `libxml2` version is out of sync between `xmlsec` and `lxml`. I've personally found this fairly difficult to get right, and I think this is evidenced by most of the CI builds failing because of this issue.

**Comment by jimjag** [comment]
#299 has been merged... I'll start looking into PyPI access

**Comment by jimjag** [comment]
I have PyPI access... well, at least an account. So let's start with the release process. Coordinating w/ xmlsec makes sense.

**Comment by mxamin** [comment]
I created a pre-release https://github.com/xmlsec/python-xmlsec/releases/tag/1.3.14-rc1
Please test it and let me know if there's something missing.
I guess we can release the official next version sometime next week if nothing changes

I couldn't create the prebuilt wheels for Windows, I had trouble using Appveyor so any help with that is appreciated :)

We still need access to python-xmlsec official pypi (https://pypi.org/project/xmlsec/). @bgaifullin, @hoefling, @mehcode Can you add me as a maintainer so I can upload the new release.

**Comment by mxamin** [comment]
@bgaifullin @hoefling @mehcode Any update regarding the access to pypi?

**Comment by vacarme** [comment]
the pre-release fixes the installation issue using pip on macOs 14.4 M1 👍

**Comment by jimjag** [comment]
Just a FYI that I'll be traveling from Apr15->May1 with limited 'net access

**Comment by bgaifullin** [comment]
Sorry for delay.

**Comment by bgaifullin** [comment]
Send invitation to [mxamin](https://github.com/mxamin)  and [jimjag](https://github.com/jimjag)
Please check your mailbox.

**Comment by mxamin** [comment]
> Send invitation to [mxamin](https://github.com/mxamin) and [jimjag](https://github.com/jimjag) Please check your mailbox.

Thanks a lot @bgaifullin

**Comment by oussjarrousse** [comment]
white smoke?

**Comment by mxamin** [comment]
Update: I'm working on preparing windows wheels, I hope I can finish it by the end of this week. If so we will release the new version.

**Comment by mxamin** [comment]
I released the new version
