### ISSUE TITLE
Python 3.13 wheels

### ISSUE THREAD

**Issue by nijel** [xmlsec/python-xmlsec#327]
Can you please publish wheels for Python 3.13? Without these, it's pretty easy to run into libxml mismatch errors.

Python 3.13. is now RC (what means ABI stable), cibuildwheel supports building wheels for several months, and final Python 3.13 should be released next week.

**Comment by jameslao** [comment]
This will be highly appreciated

**Comment by IgnacioMaestro** [comment]
I can't see the wheels publised in pip: https://pypi.org/project/xmlsec/#files

**Comment by agronholm** [comment]
One of the wheel jobs is failing: https://github.com/xmlsec/python-xmlsec/actions/runs/11830357391/job/32963732673

**Comment by nijel** [comment]
I see the tag is there (https://github.com/xmlsec/python-xmlsec/releases/tag/1.3.15), but PyPI still has 1.3.14: https://pypi.org/project/xmlsec/

**Comment by jimjag** [comment]
Yes, we need one of the other maintainers with PyPI access to update.
